version: '3.7'

services:
  $CI_PROJECT_NAME:
    image: $IMAGE_NAME
    restart: unless-stopped
    ports:
      - 80
    volumes:
      - ./config.json:/usr/share/nginx/html/config.json
    environment:
      VIRTUAL_HOST: react-starter.$URL
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost/index.html']
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 15s

networks:
  default:
    external:
      name: nginx-proxy
