import { paymentLogs } from './../../../data/Payment.data';
export enum AuthRoute {
  dashboard = '/',
  companies = '/companies',
  policyReviewRequest = '/policy-review-request',
  standardPolicies = '/standard-policies',
  standardPolicyDetail = '/standard-policies/:standardPolicyId',
  oldPolicies = '/old-policies',
  oldPolicyDetails = '/old-policies/:oldPolicyDetailId',
  policyReviewRequestDetail = '/policy-review-request/:requestId',
  editCompany='/companies/company-id-here/edit',
  companyClerkDetails='/company-clerks/:companyClerkId',
  lawOfficeInfoDetails='/law-office-infos/:lawOfficeInfoId',
  companyClerk = '/company-clerks',
  Lawyers = '/lawyers',
  lawofficeinfos = '/law-office-infos',
  checkEligibilityResponse = '/check-eligibility-responses',
  cities = '/cities',
  invoices = '/invoices',
  unifiedinvoicelogs = '/unified-invoicelogs',
  paymentLogs = '/payment-logs',
  paymentStatusLogs = '/payment-status-logs',
  adminuser = '/admin-users',
  settings = '/settings',
  activityRecords = '/activity-records',
  statistics = '/statistics',
  contactInformation = '/mlsd_contact_infos',
  lawyerDetails = '/lawyers/:lawyerDetailId',
  checkEligibilityResponseDetails = '/check-eligibility-responses/:eligibilityResponseId',
  cityDetails = '/cities/:cityId',
  adminUserDetails = '/admin-users/:adminUser',
  invoiceDetails = '/invoices/:invoiceId',
  paymentStatusLogDetails = `/payment-status-logs/:paymentStatusLogId`,
  settingDetails = `/settings/:settingId`
}
