export enum AuthRoute {
  dashboard = '/',
  companies = '/companies',
  policyReviewRequest = '/policy-review-request/:requestId',
  companyClerk = '/company-clerks',
  lawofficeinfos = '/law-office-infos',
  contactInformation = '/mlsd_contact_infos',
  activityRecords = '/activity-records',
  example = '/example',
  exampleMikro = '/example-mikro',
  exampleModuleFederation = '/example-module-federation',
  exampleProcess = '/example-process',
  exampleLawOffice = '/example-law-office',
  exampleLawOfficeHome = '/example-law-office-home',
  exampleLawOfficeWorkPolicies = '/example-law-office-work-policies',
  exampleAccounWithNavigation = '/example-account-with-navigation',
}
