import { paymentLogs } from './../../../data/Payment.data';
export enum AuthRoute {
  dashboard = '/',
  companies = '/companies',
  policyReviewRequest = '/policy-review-request',
  standardPolicies = '/standard-policies',
  oldPolicies = '/old-policies',
  policyReviewRequestDetail = '/policy-review-request/:requestId',
  companyClerk = '/company-clerks',
  Lawyers = '/lawyers',
  lawofficeinfos = '/law-office-infos',
  checkEligibilityResponse = '/check-eligibility-responses',
  cities = '/cities',
  invoices = '/invoices',
  unifiedinvoicelogs = '/unified_invoice_logs',
  paymentLogs = '/payment-logs',
  paymentStatusLogs = '/payment-status-logs',
  adminuser = '/admin-users',
  contactInformation = '/mlsd_contact_infos',
  settings = '/settings',
  activityRecords = '/activity-records',
  statistics = '/statistics',
}
