#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

local_branch="$(git rev-parse --abbrev-ref HEAD)"
valid_branch_regex="^(feature|bugfix|improvement)\/.*$"
message="Branch names in this project must adhere to this contract: $valid_branch_regex. Your commit will be rejected. You should rename your branch to a valid name and try again."

if [[ ! $local_branch =~ $valid_branch_regex ]]
then
    echo "$message"
    exit 1
fi

# npx lint-staged
# npm run type-check
# npm run test:unit
